server:
  port: 8081
spring:
  application:
    name: auth-service
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.<region>.amazonaws.com/<user-pool-id>
integration:
  portal:
    connectionRequestTimeout: 10000
    connect-timeout: 10000
    read-timeout: 10000
    secret-key:
      value: IiK7ofVZTJwFu41Gezo3mlq2RnDDoTTFourIV2hvaiF0AyCnvy6IBzHPc7j5fcCn
    data-service:
      base-url: http://localhost:8085/data-service
      get-config:
        url: ${integration.portal.data-service.base-url}/api/v1/config
aws:
  cognito:
    userPoolId: userPoolId
    clientId: clientId
    region: region

