server:
  port: 8085
spring:
  application:
    name: data-service
  profiles:
    active: dev
integration:
  portal:
    connectionRequestTimeout: 10000
    connect-timeout: 10000
    read-timeout: 10000
    secret-key:
      value: IiK7ofVZTJwFu41Gezo3mlq2RnDDoTTFourIV2hvaiF0AyCnvy6IBzHPc7j5fcCn