server:
  port: 8085
spring:
  application:
    name: data-service
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    password: # Optional
    database: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/demotcb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
integration:
  portal:
    connectionRequestTimeout: 10000
    connect-timeout: 10000
    read-timeout: 10000
    secret-key:
      value: IiK7ofVZTJwFu41Gezo3mlq2RnDDoTTFourIV2hvaiF0AyCnvy6IBzHPc7j5fcCn