server:
  port: 8083
spring:
  application:
    name: policy-service
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 10000
            connectTimeout: 10000
            loggerLevel: FULL
  redis:
    host: localhost
    port: 6379
    password: # Optional
    database: 0
integration:
  portal:
    secret-key:
      value: IiK7ofVZTJwFu41Gezo3mlq2RnDDoTTFourIV2hvaiF0AyCnvy6IBzHPc7j5fcCn
    data-service:
      base-url: http://localhost:8085/api/v1/data_master
      get-config:
        url: ${integration.portal.data-service.base-url}/api/v1/config
    integration-service:
      base-url: http://localhost:8086/integration-service/api/v1/policy
      get-config:
        url: ${integration.portal.integration-service.base-url}/api/v1/config
feign:
  client:
    config:
      default:
        loggerLevel: full