server:
  port: 8084
spring:
  application:
    name: lead-service
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 10000
            connectTimeout: 10000
            loggerLevel: FULL

integration:
  portal:
    secret-key:
      value: IiK7ofVZTJwFu41Gezo3mlq2RnDDoTTFourIV2hvaiF0AyCnvy6IBzHPc7j5fcCn
    data-service:
      base-url: http://localhost:3000/data-service