server:
  port: 8086
spring:
  application:
    name: integration-service
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 10000
            connectTimeout: 10000
            loggerLevel: FULL
integration:
  portal:
    connectionRequestTimeout: 10000
    connect-timeout: 10000
    read-timeout: 10000
    secret-key:
      value: IiK7ofVZTJwFu41Gezo3mlq2RnDDoTTFourIV2hvaiF0AyCnvy6IBzHPc7j5fcCn
    data-service:
      base-url: http://localhost:8085/api/v1/data_master
      get-config:
        url: ${integration.portal.data-service.base-url}/api/v1/config
data-service:
  url: http://localhost:8085